name: Deploy Widget to stage

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: npm

            - name: Npm install
              run: npm ci

            - name: 'Build app'
              run: npm run build

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1

            - name: Upload to S3
              run: aws s3 sync ./public/ s3://widgetdev.speechki.org/ --delete --acl bucket-owner-full-control
